tracker/urls.py
# Django
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

# Project
from IssueTracker.tracker.views import search, ajax_ticket_list, new_ticket, ticket, my_tickets

urlpatterns = patterns('',
    (r'^search$', search),
    (r'^ajax/search/$', ajax_ticket_list),
    (r'^new$', new_ticket),
    (r'^(?P<pk>[\d]+)$$', ticket),
    (r'^$', my_tickets),
)

urls.py
# Django
from django.conf.urls.defaults import *
from django.contrib import admin
import django.contrib.auth.views
from django.conf import settings
from django.views.generic.simple import direct_to_template
admin.autodiscover()

# Project
from IssueTracker.tracker.views import password_done, register, home

urlpatterns = patterns('',
    (r'^tickets/', include('IssueTracker.tracker.urls')),
    (r'^ticket/', include('IssueTracker.tracker.urls')),
    (r'^workflow/', include('IssueTracker.workflow.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^faq$', direct_to_template, {'template': 'faq.html'}),
    (r'^login$', 'django.contrib.auth.views.login', 
        {'template_name':'login.html'}),
    (r'^exit$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    (r'^password/reset$', 'django.contrib.auth.views.password_reset',
        {'template_name':'password_reset_form.html',
        'email_template_name':'password_reset_email.html'}),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name':'password_reset_done.html'}),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name':'password_reset_confirm.html'}),
    (r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name':'password_reset_complete.html'}),
    (r'^password$', 'django.contrib.auth.views.password_change',
        {'template_name':'password.html',
        'post_change_redirect':'/password_done'}),
    (r'^password_done$', password_done),
    (r'^signup$', register),
    (r'^signup_done$', direct_to_template, {'template': 'signup_done.html'}),
    (r'^$', home),
)

if settings.DEBUG:
    urlpatterns = patterns('',
            (r'^static/(?P<path>.*)$',
                'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT}),
        ) + urlpatterns

tracker/models.py
# -*- coding: UTF-8 -*-
"""
Models for the Tracker application: simply represent a ticket type, and tickets.
"""
# Python
import datetime

# Django
from django.db import models
from django.utils.translation import ugettext_lazy as _, ugettext as __
from django.contrib.auth.models import User
import django.dispatch

# IssueTracker
from workflow.models import Workflow, WorkflowManager
from project.models import Project, Component

#########
# Signals
#########

# Fired whenever a new ticket is created
ticket_created = django.dispatch.Signal()
# Fired whenever a ticket is updated
ticket_updated = django.dispatch.Signal()

########
# Models
########

class TicketType(models.Model):
    """
    Represents a type of ticket that can be created in the system 
    """
    name = models.CharField(
            _('Name'),
            max_length=64
            )
    description = models.TextField(
            _('Description'),
            blank=True
            )
    workflow = models.ForeignKey(
            Workflow,
            help_text=_('The default workflow to use with a ticket of this type')
            )

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name',]
        verbose_name = _('Ticket Type')
        verbose_name_plural = _('Ticket Types')

class Ticket(models.Model):
    """
    Represents a ticket in the issue tracker 
    """
    ticket_type = models.ForeignKey(TicketType)
    project = models.ForeignKey(Project)
    component = models.ForeignKey(Component)
    summary = models.CharField(
            _('Summary'),
            max_length=256,
            help_text=_('A brief summary of the ticket')
            )
    description = models.TextField(
            _('Description')
            )
    workflow_manager = models.ForeignKey(WorkflowManager)
    created_by = models.ForeignKey(
            User,
            related_name='tickets_created' )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(
            User,
            related_name='tickets_updated')
    updated_on = models.DateTimeField(auto_now=True)
    assigned_to = models.ForeignKey(
            User,
            related_name='tickets_assigned',
            limit_choices_to={'is_staff': True},
            null=True
            )

    def __unicode__(self):
        return self.summary

    def save(self):
        if self.id == None:
            ticket_created.send(sender=self)
        super(Ticket, self).save()
        ticket_updated.send(sender=self)

    class Meta:
        ordering = ['-updated_on','-created_on']
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')

tracker/forms.py
# -*- coding: UTF-8 -*-
# Django
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User

# Project
from models import Ticket

###########################
# Bespoke ModelChoice field
###########################
class AssigneeUserChoice(forms.ModelChoiceField):
    """
    Makes sure the User model returns something meaningful to the user instead
    of the __unicode__() call.
    """
    def label_from_instance(self, obj):
        return obj.get_full_name()

#######
# Forms
#######
class RegistrationForm(forms.Form):
    """ For user registration"""
    username = forms.CharField(max_length=30,
            widget=forms.TextInput(attrs={'class':'focus'}),
            label=_('Username'))
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                widget=forms.PasswordInput)
    email = forms.EmailField(label=_('Email Address'), 
            help_text=_('e.g. name@company.com'))
    first_name = forms.CharField(max_length=30,
            label=_('First name'))
    last_name = forms.CharField(max_length=30,
            label=_('Last name'))

    def clean_username(self):
        """ Make sure we don't have any duplicate usernames """
        uname = self.cleaned_data['username']
        if User.objects.filter(username__exact=uname):
            raise forms.ValidationError(
                    _("A user with this username already exists"))
        return uname

    def clean_email(self):
        """ Make sure we don't have any duplicate emails"""
        email = self.cleaned_data['email']
        if User.objects.filter(email__exact=email):
            raise forms.ValidationError(
                    _("A user with this email address already exists"))
        return email 

    def clean_password2(self): 
        password = self.cleaned_data.get("password", "") 
        password2 = self.cleaned_data["password2"] 
        if password != password2: 
            raise forms.ValidationError(_("The two password fields didn't"\
                    " match.")) 
        return password2

class SearchForm(forms.Form):
    """
    For searching for tickets
    """
    searchbox = forms.CharField(max_length=256,
            widget=forms.TextInput(attrs={'class':'focus', 'size':'55'}),
            label='Search (use keywords)',
            required=True,
            error_messages={ 
                'required': _('Please enter something to search for') 
                }
            )

class TicketForm(forms.ModelForm):
    """
    For creating new tickets
    """
    class Meta:
        model = Ticket
        exclude = ('workflow_manager', 'created_by', 'created_on', 'updated_by',
                'updated_on', 'assigned_to')

class AssignForm(forms.Form):
    """
    For selecting who to assign the ticket to
    """
    assignee = AssigneeUserChoice(
            queryset = User.objects.filter(is_staff=True)
            )

class StateForm(forms.Form):
    """
    For selecting the next state to move to in the workflow
    """
    def __init__(self, *args, **kwargs):
        wm = kwargs['workflow_manager']
        del kwargs['workflow_manager']
        super(StateForm, self).__init__(*args, **kwargs)
        self.fields['transition'].queryset = wm.current_state().state.transitions_from.all()

    transition = forms.ModelChoiceField(queryset = None) 

tracker/templates/my_tickets.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'My Tickets'%}{% endblock %}
{% block content %}
<h2>{% trans "My Tickets" %}</h2>
{% if results %}
<table>
    <tr>
        <th scope="column">{% trans "Ticket Number" %}</th>
        <th scope="column">{% trans "Ticket Type" %}</th>
        <th scope="column">{% trans "Summary" %}</th>
        <th scope="column">{% trans "Created on" %}</th>
        <th scope="column">{% trans "Created by" %}</th>
        <th scope="column">{% trans "Current State" %}</th>
        <th>&nbsp;</th>
    </tr>
    {% for item in results %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.ticket_type}}</td>
        <td>{{item.summary}}</td>
        <td>{{item.created_on|date:"D d M Y"}}</td>
        <td>{{item.created_by.get_full_name}}</td>
        <td>{{item.workflow_manager.current_state.state}}</td>
        <td><a href="/ticket/{{item.id}}">{% trans "View" %}</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p><big><strong><span class="red">{% blocktrans %}
You don't appear to be associated with any tickets at this moment in time.
Please try again later.
{% endblocktrans %}</span></strong></big></p>
{% endif %}
{% endblock %}

tracker/templates/new.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'New Ticket'%}{% endblock %}
{% block jquery_ready %}
$("#id_ticket_type").focus();
{% endblock %}
{% block content %}
<h1>{% trans "New Ticket" %}</h1>
<p>{% blocktrans %}
To report an issue create a new ticket by filling in the form below. Please
provide as much information as possible. It is helpful if you:
{% endblocktrans %}</p>
<ul>
    <li>{% trans "Explain how to recreate any problems" %}</li>
    <li>{% trans "Describe what actually happens vs. what you expect" %}</li>
    <li>{% trans "Identify exactly what the issue is about. Be specific" %}</li>
    <li>{% trans "Provide a justification for any enhancements" %}</li>
</ul>
<form method="POST" action="/tickets/new">
    {{form.as_p}}
    <p><input type="submit" value="{% trans 'Create' %}" /> |
    <a href="/">{% trans "Home" %}</p>
</form>
{% endblock %}

tracker/templates/new_ticket_email.html
{% load i18n %}
{% blocktrans %}You're receiving this automated e-mail because you have 
recently submitted a new ticket at the IssueTracker site.{%endblocktrans%}

{% trans "Summary" %}: {{ticket.summary}}

{% trans "Description" %}: {{ticket.description}}

{% trans "You can view the status of this ticket at the folloiwng page:"%}
{% block reset_link %}
{{ protocol }}://{{ domain }}/ticket/{{ticket.id}}
{% endblock %}

{% trans "Thanks for using our site!"%}

tracker/templates/search.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Search'%}{% endblock %}
{% block javascript_includes %}
<script src="/static/javascript/jquery.autocomplete.js" type="text/javascript"></script>
<script type="text/javascript">
    $("#id_searchbox").autocomplete('/tickets/ajax/search/');
</script>
{% endblock %}
{% block jquery_ready %}
$("#id_searchbox").focus();
{% endblock %}
{% block content %}
<h2>{% trans "Search for Issues" %}</h2>
<form method="POST" action="/tickets/search">
    <p>
    {{form.searchbox.errors}}
    {{form.searchbox.label_tag}} {{form.searchbox}}
    <input type="submit" value="{% trans 'Search' %}" />
    </p>
</form>
{% if results %}
<h2>{% trans "Results" %}</h2>
<table>
    <tr>
        <th scope="column">{% trans "Ticket Number" %}</th>
        <th scope="column">{% trans "Ticket Type" %}</th>
        <th scope="column">{% trans "Summary" %}</th>
        <th scope="column">{% trans "Created on" %}</th>
        <th scope="column">{% trans "Created by" %}</th>
        <th scope="column">{% trans "Current State" %}</th>
        <th>&nbsp;</th>
    </tr>
    {% for item in results %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.ticket_type}}</td>
        <td>{{item.summary}}</td>
        <td>{{item.created_on|date:"D d M Y"}}</td>
        <td>{{item.created_by.get_full_name}}</td>
        <td>{{item.workflow_manager.current_state}}</td>
        <td><a href="/ticket/{{item.id}}">{% trans "View" %}</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p><big><strong><span class="red">{% blocktrans %}
Unable to find any matching results. Please try again and use different search
terms.
{% endblocktrans %}</span></strong></big></p>
{% endif %}
{% endblock %}

tracker/templates/ticket.html
{% extends "base.html" %}
{% load i18n %}
{% load comments %}
{% block title %}{% trans 'View Ticket'%}{% endblock %}
{% block jquery_ready %}
$("#id_ticket_type").focus();
{% endblock %}
{% block content %}
<p><strong>{% trans "Ticket Number:" %}</strong> {{ticket.id}}
<strong>{% trans "Current State:" %}</strong>
{{ticket.workflow_manager.current_state.state}}</p>
{% if ticket.workflow_manager.completed_on %}
<p><span class="red">{% trans "Completed on:"%} 
    {{ticket.workflow_manager.completed_on|date:" D d M Y"}}</span></p>
{% else %}
{% if user.is_staff %}
<form action="/ticket/{{ticket.id}}" method="post">
<p><strong>{% trans "Assign to:" %}</strong>
{{assignform.assignee}}
<input type="submit" name="assign" value="Assign">
</p>
</form>
{% endif %}
{% ifequal user ticket.assigned_to %}
<form action="/ticket/{{ticket.id}}" method="post">
<p><strong>{% trans "Change state:" %}</strong>
{{stateform.transition}}
<input type="submit" name="change" value="Change">
</p>
</form>
{% endifequal %}
{% endif %}
<h1>{{ticket.summary}}</h1>
<p>{{ticket.description|escape|linebreaks}}</p>
<h2>{% trans "Comments" %}</h2>
{% get_comment_list for tracker.ticket ticket.id as comment_list %}
{% if comment_list %}
{% for comment in comment_list %}
<p><strong>{{comment.user.get_full_name}}</strong> {% trans "commented, on" %}
{{ comment.submit_date|date:"F j, Y" }} {% trans "at" %} 
{{ comment.submit_date|date:"P" }}:<br/>
{{ comment.comment|escape|urlizetrunc:40|linebreaks }}
</p>
{% endfor %}
{% else %}
<p>{% trans "There are no comments associated with this ticket." %}</p>
{% endif %}
{% if ticket.workflow_manager.completed_on %}
<h3>{% trans "Comments closed"%}</h3>
{% else %}
<h3>{% trans "Post a Comment" %}</h3>
{% get_comment_form for tracker.ticket ticket.id as form %}
<form action="/comments/post/" method="post">
    <p>{{form.comment}}</p>
    {{form.content_type}}
    {{form.object_pk}}
    {{form.timestamp}}
    {{form.security_hash}}
    <input type="hidden" name="next" value="/ticket/{{ticket.id}}" id="id_next"/>
    <p><input type="submit" name="post" value="Post Comment" /> |
    <a href="/">{% trans "Home" %}</a> |
    <a href="/tickets">{% trans "My Tickets" %}</a></p>
</form>
{% endif %}
{% endblock %}