urls.py
# Django
from django.conf.urls.defaults import *
from django.contrib import admin
import django.contrib.auth.views
from django.conf import settings
from django.views.generic.simple import direct_to_template
admin.autodiscover()

# Project
from IssueTracker.tracker.views import password_done, register, home

urlpatterns = patterns('',
    (r'^tickets/', include('IssueTracker.tracker.urls')),
    (r'^ticket/', include('IssueTracker.tracker.urls')),
    (r'^workflow/', include('IssueTracker.workflow.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^faq$', direct_to_template, {'template': 'faq.html'}),
    (r'^login$', 'django.contrib.auth.views.login', 
        {'template_name':'login.html'}),
    (r'^exit$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    (r'^password/reset$', 'django.contrib.auth.views.password_reset',
        {'template_name':'password_reset_form.html',
        'email_template_name':'password_reset_email.html'}),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name':'password_reset_done.html'}),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name':'password_reset_confirm.html'}),
    (r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name':'password_reset_complete.html'}),
    (r'^password$', 'django.contrib.auth.views.password_change',
        {'template_name':'password.html',
        'post_change_redirect':'/password_done'}),
    (r'^password_done$', password_done),
    (r'^signup$', register),
    (r'^signup_done$', direct_to_template, {'template': 'signup_done.html'}),
    (r'^$', home),
)

if settings.DEBUG:
    urlpatterns = patterns('',
            (r'^static/(?P<path>.*)$',
                'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT}),
        ) + urlpatterns

tracker/forms.py
# -*- coding: UTF-8 -*-
# Django
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User

# Project
from models import Ticket

###########################
# Bespoke ModelChoice field
###########################
class AssigneeUserChoice(forms.ModelChoiceField):
    """
    Makes sure the User model returns something meaningful to the user instead
    of the __unicode__() call.
    """
    def label_from_instance(self, obj):
        return obj.get_full_name()

#######
# Forms
#######
class RegistrationForm(forms.Form):
    """ For user registration"""
    username = forms.CharField(max_length=30,
            widget=forms.TextInput(attrs={'class':'focus'}),
            label=_('Username'))
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                widget=forms.PasswordInput)
    email = forms.EmailField(label=_('Email Address'), 
            help_text=_('e.g. name@company.com'))
    first_name = forms.CharField(max_length=30,
            label=_('First name'))
    last_name = forms.CharField(max_length=30,
            label=_('Last name'))

    def clean_username(self):
        """ Make sure we don't have any duplicate usernames """
        uname = self.cleaned_data['username']
        if User.objects.filter(username__exact=uname):
            raise forms.ValidationError(
                    _("A user with this username already exists"))
        return uname

    def clean_email(self):
        """ Make sure we don't have any duplicate emails"""
        email = self.cleaned_data['email']
        if User.objects.filter(email__exact=email):
            raise forms.ValidationError(
                    _("A user with this email address already exists"))
        return email 

    def clean_password2(self): 
        password = self.cleaned_data.get("password", "") 
        password2 = self.cleaned_data["password2"] 
        if password != password2: 
            raise forms.ValidationError(_("The two password fields didn't"\
                    " match.")) 
        return password2

class SearchForm(forms.Form):
    """
    For searching for tickets
    """
    searchbox = forms.CharField(max_length=256,
            widget=forms.TextInput(attrs={'class':'focus', 'size':'55'}),
            label='Search (use keywords)',
            required=True,
            error_messages={ 
                'required': _('Please enter something to search for') 
                }
            )

class TicketForm(forms.ModelForm):
    """
    For creating new tickets
    """
    class Meta:
        model = Ticket
        exclude = ('workflow_manager', 'created_by', 'created_on', 'updated_by',
                'updated_on', 'assigned_to')

class AssignForm(forms.Form):
    """
    For selecting who to assign the ticket to
    """
    assignee = AssigneeUserChoice(
            queryset = User.objects.filter(is_staff=True)
            )

class StateForm(forms.Form):
    """
    For selecting the next state to move to in the workflow
    """
    def __init__(self, *args, **kwargs):
        wm = kwargs['workflow_manager']
        del kwargs['workflow_manager']
        super(StateForm, self).__init__(*args, **kwargs)
        self.fields['transition'].queryset = wm.current_state().state.transitions_from.all()

    transition = forms.ModelChoiceField(queryset = None) 

templates/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>{% trans "Bugz" %} - {% block title %}{% trans "An Issue Tracker"%}{% endblock %}</title>
        <meta content="text/html; charset=utf-8" http-equiv="content-type" />
        <link rel="shortcut icon" href="/static/images/bugz.ico" />
        <link rel="stylesheet" title="Normal" media="screen" type="text/css" href="/static/css/style.css" />
        {% block css_includes %}{% endblock %}
    </head>
    <body>
        <div id="container">
            {% block header %}
            <div id="header">
                <img src="/static/images/logo.jpg" alt="Bugz-logo"/>
                <div id="menu">
                {% block menu %}
                {% include "menu.html" %}
                {% endblock %}
                </div> <!-- end menu -->
            </div> <!-- end header -->
            {% endblock %}
            {% if messages %}
            {% for msg in messages %}
            <div class="message">
                <p>{{msg}}</p>
            </div>
            {% endfor %}
            {% endif %}
            <div id="content">
            {% block content %}
                <h1>Test Card</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
                do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                dolor in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est
                laborum.</p>
                <h2>Lists</h2>
                <h3>Ordered</h3>
                <ol>
                    <li>Item 1</li>
                    <li>Item 2</li>
                    <li>Item 3</li>
                </ol>
                <h3>Unordered</h3>
                <ul>
                    <li>Item 1</li>
                    <li>Item 2</li>
                    <li>Item 3</li>
                </ul>
                <h2>Various Elements</h2>
                <p>Within this piece of text we must make sure we can 
                <a href="#">display a link correctly</a>, <em>emphasis</em>,
                <strong>strong</strong>, <big>BIG</big> and
                <small>small</small>.</p>
                <h2>Table</h2>
                <table>
                    <caption>An example table</caption>
                    <tr>
                        <th scope="column">Header 1</th>
                        <th scope="column">Header 2</th>
                        <th scope="column">Header 3</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr class="alt">
                        <td>Column 1, Item 1</td>
                        <td>Column 2, Item 1</td>
                        <td>Column 3, Item 1</td>
                        <td><a href="#">link</a></td>
                    </tr>
                    <tr>
                        <td>Column 1, Item 2</td>
                        <td>Column 2, Item 2</td>
                        <td>Column 3, Item 2</td>
                        <td><a href="#">link</a></td>
                    </tr>
                    <tr class="alt">
                        <td>Column 1, Item 3</td>
                        <td>Column 2, Item 3</td>
                        <td>Column 3, Item 3</td>
                        <td><a href="#">link</a></td>
                    </tr>
                    <tr>
                        <td>Column 1, Item 4</td>
                        <td>Column 2, Item 4</td>
                        <td>Column 3, Item 4</td>
                        <td><a href="#">link</a></td>
                    </tr>
                </table>
            {% endblock %}
            </div> <!-- END CONTENT -->
            <div id="footer">
                <p>{% blocktrans %}
                Bugz is &copy; 2009 
                <a href="http://ntoll.org/">Nicholas H.Tollervey.</a>
                {% endblocktrans %}<br/>
                <a href="http://validator.w3.org/check?uri=referer"><img src="/static/images/w3c-xhtml.png" alt="Valid XHTML 1.0 Strict" /></a>
                <a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="/static/images/w3c-css.png" alt="Valid CSS!" /></a></p>
            </div> <!-- END FOOTER -->
        </div><!-- END CONTAINER -->
        <!-- Javascript -->
        <script src="/static/javascript/jquery-1.3.2.min.js" type="text/javascript"></script>
        {% block javascript_includes %}{% endblock %}
        <script type="text/javascript">
            //<![CDATA[
            $(document).ready(function(){
            {% block jquery_ready %}{% endblock %}
            });
            //]]>
        </script>
        <!-- END Javascript -->
    </body>
</html>

templates/faq.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Frequently Asked Questions'%}{% endblock %}
{% block content %}
<h1>{% trans "Frequently Asked Questions" %}</h1>
<ul>
    <li><a href="#1">{% trans "What is IssueTracker?" %}</a></li>
    <li><a href="#2">{% trans "Who wrote IssueTracker?" %}</a></li>
    <li><a href="#3">{% trans "Why write yet another issue tracker?" %}</a></li>
    <li><a href="#4">{% trans "How much does it cost?" %}</a></li>
    <li><a href="#5">{% trans "What about the workflow engine?" %}</a></li>
    <li><a href="#6">{% trans "I want to give feedback! How?" %}</a></li>
</ul>
<h2 id="1">{% trans "What is IssueTracker?" %}</h2>
<p>{% blocktrans %}IssueTracker is a <strong>very</strong> simple issue tracking
application written using the <a href="http://www.djangoproject.com/">Django</a>
web framework and a bespoke workflow engine.
{% endblocktrans %}</p>
<h2 id="2">{% trans "Who wrote IssueTracker?" %}</h2>
<p>{% blocktrans %}<a href="http://ntoll.org">Nicholas Tollervey</a> wrote this
software over a period of two days as an academic exercise.
{% endblocktrans %}</p>
<h2 id="3">{% trans "Why write yet another issue tracker?" %}</h2>
<p>{% blocktrans %}Like I just said, as an academic exercise. My aim being to
use the workflow engine "in anger" so I get a feel for how helpful it is to code
against. Hopefully, the pain I encountered when writing this will inform me when
updating the project.
{% endblocktrans %}</p>
<h2 id="4">{% trans "How much does it cost?" %}</h2>
<p>{% blocktrans %}Nothing. :-)
{% endblocktrans %}</p>
<h2 id="5">{% trans "What about the workflow engine?" %}</h2>
<p>{% blocktrans %}The workflow engine is a generic application that I can
"drop in" to any Django based web-application. The only thing needed to finish
it off is a set of forms and UI views to make creating and editing workflow
easier (rather than having to use the Django admin area).
{% endblocktrans %}</p>
<h2 id="6">{% trans "I want to give feedback! How?" %}</h2>
<p>{% blocktrans %}My contact details can be found here: <a
    href="http://ntoll.org/contact">http://ntoll.org/contact</a>.
{% endblocktrans %}</p>
<p><a href="/">{% trans "Home" %}</a></p>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Home'%}{% endblock %}
{% block css_includes %}
<style type="text/css" media="screen, projection">
@import url(/static/css/jq_fade.css);
</style>
{% endblock %}
{% block javascript_includes %}
{% if user.is_authenticated %}
<script src="/static/javascript/jquery.autocomplete.js" type="text/javascript"></script>
<script type="text/javascript">
    $("#id_searchbox").autocomplete('/tickets/ajax/search/');
</script>
{% else %}
<script src="/static/javascript/jquery.innerfade.js" type="text/javascript"></script>
{% endif %}
{% endblock %}
{% block jquery_ready %}
{% if user.is_authenticated %}
$("#id_searchbox").focus();
{% else %}
	$('ul#portfolio').innerfade({
						speed: 1000,
						timeout: 5000,
						type: 'sequence',
						containerheight: '220px'
    });
{% endif %}
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<h1>{% trans "Hello" %} {{ user.first_name }}!</h1>
<p>{% blocktrans %}
Welcome to Bugz...
{% endblocktrans %}</p>
<h2>{% trans "Search for Issues" %}</h2>
<form method="POST" action="/tickets/search">
    <p>
    {{form.searchbox.errors}}
    {{form.searchbox.label_tag}} {{form.searchbox}}
    <input type="submit" value="{% trans 'Search' %}" />
    </p>
</form>
{% else %}
    <div id="fading_images">
       <ul id="portfolio" style="list-style-type: none;">					
					<li>
						<a href="http://www.flickr.com/photos/chaparral/382859222/"><img src="/static/images/screen1.jpg" alt="Having issues with 'Issues'..? Confused by bug tracking..?" /></a>
					</li>
					<li>
						<a href="http://www.flickr.com/photos/dotbenjamin/2765083201/"><img src="/static/images/screen2.jpg" alt="Bugz makes tracking issues EASY!" /></a>
					</li>					
					<li>
						<a href="http://www.flickr.com/photos/zanastardust/2481428401/"><img src="/static/images/screen3.jpg" alt="Elegant &amp; Simple" /></a>
					</li>					
					<li>
						<a href="http://www.flickr.com/photos/yogi/1474419777/"><img src="/static/images/screen4.jpg" alt="Keep your geeks HAPPY (use Bugz ;-)" /></a>
					</li>		
       </ul>
   </div>

<p class="what_next">
   <a href="/signup">{% trans "Signup" %}</a> |
   <a href="/login">{% trans "Login" %}</a> |
   <a href="/faq">{% trans "FAQ" %}</a> 
</p>
{% endif %}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Login'%}{% endblock %}
{% block jquery_ready %}
$("#id_username").focus(); 
{% endblock %}
{% block content %}
<h1>Login</h1>
<p>{% blocktrans %}
Please enter your username and password into the form below:
{% endblocktrans %}</p>
{% if form.errors %}
<p><span class="red">{% blocktrans %}
Your username and password didn't match. Please try again.
{% endblocktrans %}</span></p>
{% endif %}
<form method="POST" action="{% url django.contrib.auth.views.login %}">
    {{form.as_p}}
    <input type="submit" value="{% trans 'login' %}" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>
<p><a href="password/reset">{% trans "Forgotten Password?" %}</a> | 
<a href="/">{% trans "Home" %}</a></p>
{% endblock %}

templates/menu.html
{% load i18n %}
{% if user.is_authenticated %}
<a href="/">{% trans "Home" %}</a> |
<a href="/tickets/">{% trans "My Tickets" %}</a> |
<a href="/tickets/new">{% trans "New Ticket" %}</a> |
<a href="/faq">{% trans "FAQ" %}</a> |
<a href="/exit">{% trans "Logout" %}</a> |
You are logged in as: <strong>{{user.get_full_name}}</strong>
{% else %}
<a href="/">{% trans "Home" %}</a> |
<a href="/signup">{% trans "Sign Up" %}</a> | 
<a href="/login">{% trans "Login" %}</a> |
<a href="/faq">{% trans "FAQ" %}</a> |
{% endif %}

templates/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}
{%block title %}{% trans "Password reset complete"%}{% endblock %}
{% block content %}
<h1>{% trans "Password reset complete"%}</h1>

<p>{% trans "Your password has been set. You may go ahead and log in now."%}</p>

<p><a href="{{ login_url }}">{% trans "Log in"%}</a></p>

{% endblock %}

templates/password_reset_confirm.html
{% extends 'base.html'%}
{% load i18n %}
{%block title %}{% trans "Password Reset"%}{% endblock %}
{% block jquery_ready %}$("#id_new_password").focus(); {% endblock %}
{% block content %}
{% if validlink %}

<h1>{% trans "Enter new password"%}</h1>

<p>{% blocktrans %}Please enter your new password twice so we can verify you 
typed it in correctly.{% endblocktrans %}</p>

<form action="" method="post">
    {{form.as_p}}
<p><input type="submit" value="{% trans "Change my password"%}"/>
</form>

{% else %}

<h1>{% trans "Password reset unsuccessful"%}</h1>

<p>{% blocktrans %}The password reset link was invalid, possibly because it has
already been used.  Please request a new password reset.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

templates/password_reset_done.html
{% extends 'base.html'%}
{% load i18n %}

{% block title %}{% trans "Password reset successful"%}{% endblock %}

{% block content %}

<h1>{% trans "Password reset successful"%}</h1>

<p>{% blocktrans %}We've e-mailed you instructions for setting your password to
the e-mail address you submitted. You should be receiving it
shortly.{%endblocktrans%}</p>
<p><a href="/">{% trans "Home" %}</a></p>
{% endblock %}

templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% trans "You're receiving this e-mail because you requested a password reset" %}
{% blocktrans %}for your user account at {{ site_name }}{% endblocktrans %}.

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url django.contrib.auth.views.password_reset_confirm uidb36=uid, token=token %}
{% endblock %}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/password_reset_form.html
{% extends 'base.html' %}
{% load i18n %}
{%block title %}{% trans "Password Reset"%}{% endblock %}
{% block jquery_ready %}$("#id_email").focus(); {% endblock %}
{% block content %}
<h1>{% trans "Password reset"%}</h1>
<p>{% blocktrans %}Forgotten your password? Enter your e-mail address below, 
and we'll e-mail instructions for setting a new one.{% endblocktrans %}</p>
<form action="" method="post">
    {{form.as_p}}
<p><input type="submit" value="{% trans "Reset my password"%}"/>
</form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load i18n %}
{%block title %}{% trans "Register New User"%}{% endblock %}
{% block jquery_ready %}
$("#id_username").focus(); 
{% endblock %}
{% block content %}
<h1>{% trans "Register New User"%}</h1>
<p>{%blocktrans%}Please enter your details below. 
{%endblocktrans%}</p>
<form method="POST" action="/signup">
    {{form.non_field_errors}}
    {{form.as_p}}
    <p><input type="submit" value="{% trans "Submit"%}"/> |
    <a href="/">{% trans "Home" %}</a>
    <input type="hidden" name="next" value="{{next}}"/></p>
</form>
{% endblock %}

templates/register_email.html
{% load i18n %}
{% blocktrans %}You're receiving this automated e-mail because you have 
registered at the IssueTracker site with the username {{user}}.{%endblocktrans%}

{% trans "Please go to the following page to login:"%}
{% block reset_link %}
{{ protocol }}://{{ domain }}/login 
{% endblock %}

{% trans "Thanks for using our site!"%}

templates/signup_done.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Signup Complete'%}{% endblock %}
{% block content %}
<h1>Signup Complete</h1>
<p>{% blocktrans %}
We have sent you instructions to the email address you have just provided
explaining how to confirm your account and set your password.
{% endblocktrans %}</p>
<p><a href="/">{% trans "Home" %}</a></p>
{% endblock %}